### ISSUE TITLE
eden: [elections] unregister all registered members when election rescheduled

### ISSUE THREAD

**Issue by brandonfancher** [eoscommunity/Eden#650]
We are moving the date of the next election up to Saturday, January 29, 2022 at 13:00 UTC. When we do this, all members election registration status should be reset to "not participating." We will require members to opt back in once the new date is set.

We have a mechanism for scheduling a new election, but we do not have the mechanism in place for resetting participation status. That's what we need.

There are a few things that must be done:

- [x] update contract to reset members' registration status to _not participating_ (#607)
- [x] backport the production version of the contract to prepare it to ship those features (#647, #648)
- [ ] update microchain code to support contract changes (#649)
- [ ] update frontend opt-in/out and elections code to handle changes introduced in contract and microchain
